// Generated by Wrangler on Fri Oct 10 2025 20:50:33 GMT-0500 (Colombia Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	MY_KV: KVNamespace;
	access_key: "";
}
