name = "astro-c"                      # nombre del proyecto Pages
pages_build_output_dir = "./dist"     # carpeta que sube Pages
compatibility_date = "2025-09-30"
compatibility_flags = ["nodejs_compat"]

[vars]
MY_VARIABLE = "Yecksinr"

[[kv_namespaces]]
binding = "MY_KV"
id = "df7b708d27464714ae3a8545aa5b0585"
preview_id = "df7b708d27464714ae3a8545aa5b0585"
remote = true

[browser]
binding = "MYBROWSER"

[ai]
binding = "AI"
remote = true

[[d1_databases]]
binding = "DB"
database_name = "igad-db"
database_id = "95d444dd-04c7-4634-a6c9-866e51bbdc94"
remote = true

# # Opcional: overrides para PREVIEW
# [[env.preview.kv_namespaces]]
# binding = "astro"
# id = "d3e7d385ad124a97bcdff6d5cf63c48b"